### ISSUE TITLE
Some question about serl？ How to solve it

### ISSUE THREAD

**Issue by ChaselLau666** [parzivar/RL#2]
/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Traceback (most recent call last):
File "/home/robo/work/serl/franka_sim/franka_sim/test/test_gym_env_human.py", line 9, in
env = envs.PandaPickCubeGymEnv(action_scale=(0.1, 1))
File "/home/robo/work/serl/franka_sim/franka_sim/envs/panda_pick_gym_env.py", line 148, in init
self._viewer.render(self.render_mode)
File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 706, in render
viewer = self._get_viewer(render_mode=render_mode)
File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 730, in _get_viewer
self.viewer = OffScreenViewer(
File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 155, in init
super().init(model, data, width, height, max_geom, visual_options)
File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 53, in init
self.viewport = mujoco.MjrRect(0, 0, width, height)
TypeError: init(): incompatible constructor arguments. The following argument types are supported:
1. mujoco._render.MjrRect(left: int, bottom: int, width: int, height: int)

Invoked with: 0, 0, None, None
Exception ignored in: <function OffScreenViewer.del at 0x7f4e525a9ea0>
Traceback (most recent call last):
File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 202, in del
self.free()
File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 199, in free
self.opengl_context.free()
File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/mujoco/egl/init.py", line 125, in free
EGL.eglDestroyContext(EGL_DISPLAY, self._context)
File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 415, in call
return self( *args, **named )
File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: EGLError(
err = EGL_NOT_INITIALIZED,
baseOperation = eglDestroyContext,
cArguments = (
<OpenGL._opaque.EGLDisplay_pointer object at 0x7f4e8def24c0>,
<OpenGL._opaque.EGLContext_pointer object at 0x7f4e526f6a40>,
),
result = 0
)
Exception ignored in: <function GLContext.del at 0x7f4e8dba9360>
Traceback (most recent call last):
File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/mujoco/egl/init.py", line 130, in del
self.free()
File "/home/robo/miniconda3/envs/serl/lib/python3.10/site-packages/mujoco/egl/init.py", line 125, in free
EGL.eglDestroyContext(EGL_DISPLAY, self._context)
File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: EGLError(
err = EGL_NOT_INITIALIZED,
baseOperation = eglDestroyContext,
cArguments = (
<OpenGL._opaque.EGLDisplay_pointer object at 0x7f4e8def24c0>,
<OpenGL._opaque.EGLContext_pointer object at 0x7f4e526f6a40>,
),
result = 0
)

**Comment by parzivar** [comment]
maybe you can try this  `pip install gymnasium < 1.0.0`
If you have any other progress, welcom discuss it.

**Comment by parzivar** [comment]
I also tried numpy==1.26.0,  which can reduce some dependency conflicts
